insert into [dbo].[region] (name) values ('Amnat Charoen');
insert into [dbo].[region] (name) values ('Margara');
insert into [dbo].[region] (name) values ('Arkalyk');
insert into [dbo].[region] (name) values ('Uuemõisa');
insert into [dbo].[region] (name) values ('Soba');
insert into [dbo].[region] (name) values ('Lalagsan');
insert into [dbo].[region] (name) values ('Karangsari');
insert into [dbo].[region] (name) values ('Bhairab Bāzār');
insert into [dbo].[region] (name) values ('Pieniężno');
insert into [dbo].[region] (name) values ('Gibsons');
insert into [dbo].[region] (name) values ('Kalibuntu');
insert into [dbo].[region] (name) values ('Bondy');
insert into [dbo].[region] (name) values ('Sugihmukti');
insert into [dbo].[region] (name) values ('Orito');
insert into [dbo].[region] (name) values ('Longshi');
insert into [dbo].[region] (name) values ('Kisumu');
insert into [dbo].[region] (name) values ('Yopal');
insert into [dbo].[region] (name) values ('Skeldon');
insert into [dbo].[region] (name) values ('Xinying');
insert into [dbo].[region] (name) values ('Ранковце');
insert into [dbo].[region] (name) values ('Sława');
insert into [dbo].[region] (name) values ('Tenkodogo');
insert into [dbo].[region] (name) values ('Cosmópolis');
insert into [dbo].[region] (name) values ('Xuebu');
insert into [dbo].[region] (name) values ('Zaña');
insert into [dbo].[region] (name) values ('Bagarmossen');
insert into [dbo].[region] (name) values ('Karak');
insert into [dbo].[region] (name) values ('Sembalunbumbung');
insert into [dbo].[region] (name) values ('Hedian');
insert into [dbo].[region] (name) values ('Babatngon');
insert into [dbo].[region] (name) values ('Houxi');
insert into [dbo].[region] (name) values ('Huilong');
insert into [dbo].[region] (name) values ('Łopuszno');
insert into [dbo].[region] (name) values ('Hongwei');
insert into [dbo].[region] (name) values ('Digos');
insert into [dbo].[region] (name) values ('Hesi');
insert into [dbo].[region] (name) values ('Lashma');
insert into [dbo].[region] (name) values ('Carpiquet');
insert into [dbo].[region] (name) values ('Novaya Derevnya');
insert into [dbo].[region] (name) values ('Nanjing');
insert into [dbo].[region] (name) values ('Gaofeng');
insert into [dbo].[region] (name) values ('Taketoyo');
insert into [dbo].[region] (name) values ('Al Mushannaf');
insert into [dbo].[region] (name) values ('Yabuli');
insert into [dbo].[region] (name) values ('Cililitan');
insert into [dbo].[region] (name) values ('Sawahan');
insert into [dbo].[region] (name) values ('Songbai');
insert into [dbo].[region] (name) values ('Quatro Barras');
insert into [dbo].[region] (name) values ('Petrich');
insert into [dbo].[region] (name) values ('Fukagawa');
insert into [dbo].[region] (name) values ('Biryulëvo Zapadnoye');
insert into [dbo].[region] (name) values ('Jintun');
insert into [dbo].[region] (name) values ('Rabāţ-e Sangī-ye Pā’īn');
insert into [dbo].[region] (name) values ('Gaowu');
insert into [dbo].[region] (name) values ('Toyooka');
insert into [dbo].[region] (name) values ('Polos');
insert into [dbo].[region] (name) values ('Soledar');
insert into [dbo].[region] (name) values ('Alor Setar');
insert into [dbo].[region] (name) values ('Lucun');
insert into [dbo].[region] (name) values ('Juliaca');
insert into [dbo].[region] (name) values ('Hengfan');
insert into [dbo].[region] (name) values ('Santa Rosa');
insert into [dbo].[region] (name) values ('Mönchengladbach');
insert into [dbo].[region] (name) values ('Si Ma Cai');
insert into [dbo].[region] (name) values ('Aso');
insert into [dbo].[region] (name) values ('Gar');
insert into [dbo].[region] (name) values ('Jadranovo');
insert into [dbo].[region] (name) values ('Huangling');
insert into [dbo].[region] (name) values ('Pasirhaur');
insert into [dbo].[region] (name) values ('Kuching');
insert into [dbo].[region] (name) values ('Wangong');
insert into [dbo].[region] (name) values ('Brodokalmak');
insert into [dbo].[region] (name) values ('Kasungu');
insert into [dbo].[region] (name) values ('Solana');
insert into [dbo].[region] (name) values ('Isakly');
insert into [dbo].[region] (name) values ('Irará');
insert into [dbo].[region] (name) values ('Yuanjiazhuang');
insert into [dbo].[region] (name) values ('Omuthiya');
insert into [dbo].[region] (name) values ('Plan de Ayala');
insert into [dbo].[region] (name) values ('Copán');
insert into [dbo].[region] (name) values ('Guaíra');
insert into [dbo].[region] (name) values ('Belyy Gorodok');
insert into [dbo].[region] (name) values ('Ndewel');
insert into [dbo].[region] (name) values ('Hutag');
insert into [dbo].[region] (name) values ('Joutseno');
insert into [dbo].[region] (name) values ('Taibao');
insert into [dbo].[region] (name) values ('Kirkland');
insert into [dbo].[region] (name) values ('Lubao');
insert into [dbo].[region] (name) values ('Uryupinsk');
insert into [dbo].[region] (name) values ('Duwe');
insert into [dbo].[region] (name) values ('Qaţanah');
insert into [dbo].[region] (name) values ('Hino');
insert into [dbo].[region] (name) values ('Łopuszna');
insert into [dbo].[region] (name) values ('Zhenjiang');
insert into [dbo].[region] (name) values ('Comal');
insert into [dbo].[region] (name) values ('Balingasag');
insert into [dbo].[region] (name) values ('Sagang');
insert into [dbo].[region] (name) values ('Leye');
insert into [dbo].[region] (name) values ('Krasnyy Profintern');
insert into [dbo].[region] (name) values ('Akzhal');
insert into [dbo].[region] (name) values ('Cibunar');
insert into [dbo].[region] (name) values ('Barbalha');
insert into [dbo].[region] (name) values ('Valdosta');
insert into [dbo].[region] (name) values ('Farasān');
insert into [dbo].[region] (name) values ('Kalāt-e Nāderī');
insert into [dbo].[region] (name) values ('Ресен');
insert into [dbo].[region] (name) values ('Bruzual');
insert into [dbo].[region] (name) values ('Niba');
insert into [dbo].[region] (name) values ('Xindai');
insert into [dbo].[region] (name) values ('Chrząstowice');
insert into [dbo].[region] (name) values ('Heshan');
insert into [dbo].[region] (name) values ('Dobryanka');
insert into [dbo].[region] (name) values ('Berezovo');
insert into [dbo].[region] (name) values ('Leles');
insert into [dbo].[region] (name) values ('Kawanoechō');
insert into [dbo].[region] (name) values ('Ebu');
insert into [dbo].[region] (name) values ('Xiaohe');
insert into [dbo].[region] (name) values ('Budapest');
insert into [dbo].[region] (name) values ('Vicente Guerrero');
insert into [dbo].[region] (name) values ('Berdorf');
insert into [dbo].[region] (name) values ('Kieta');
insert into [dbo].[region] (name) values ('Jambesari');
insert into [dbo].[region] (name) values ('Bethlehem');
insert into [dbo].[region] (name) values ('Ārt Khwājah');
insert into [dbo].[region] (name) values ('North Perth');
insert into [dbo].[region] (name) values ('Hoit Taria');
insert into [dbo].[region] (name) values ('Nowe Miasto');
insert into [dbo].[region] (name) values ('Pekan');
insert into [dbo].[region] (name) values ('Kebonagung');
insert into [dbo].[region] (name) values ('Saint-Pierre-des-Corps');
insert into [dbo].[region] (name) values ('Yuktae-dong');
insert into [dbo].[region] (name) values ('Bun Barat');
insert into [dbo].[region] (name) values ('Luci');
insert into [dbo].[region] (name) values ('Senduro');
insert into [dbo].[region] (name) values ('Regidor');
insert into [dbo].[region] (name) values ('Bang Rakam');
insert into [dbo].[region] (name) values ('Gandekan');
insert into [dbo].[region] (name) values ('Mendez-Nuñez');
insert into [dbo].[region] (name) values ('Messejana');
insert into [dbo].[region] (name) values ('Koshki');
insert into [dbo].[region] (name) values ('Bultfontein');
insert into [dbo].[region] (name) values ('Fuan');
insert into [dbo].[region] (name) values ('Vukovar');
insert into [dbo].[region] (name) values ('Guápiles');
insert into [dbo].[region] (name) values ('Molo');
insert into [dbo].[region] (name) values ('Marau');
insert into [dbo].[region] (name) values ('Guihing Proper');
insert into [dbo].[region] (name) values ('Almodôvar');
insert into [dbo].[region] (name) values ('Río Pico');
insert into [dbo].[region] (name) values ('Göteborg');
insert into [dbo].[region] (name) values ('Bereeda');
insert into [dbo].[region] (name) values ('Dananshan');
insert into [dbo].[region] (name) values ('Best');
insert into [dbo].[region] (name) values ('Kafyr-Kumukh');
insert into [dbo].[region] (name) values ('Svetlyy Yar');
insert into [dbo].[region] (name) values ('Porvoo');
insert into [dbo].[region] (name) values ('Lappeenranta');
insert into [dbo].[region] (name) values ('Gangkou');
insert into [dbo].[region] (name) values ('Tinawagan');
insert into [dbo].[region] (name) values ('Belozërsk');
insert into [dbo].[region] (name) values ('Lodja');
insert into [dbo].[region] (name) values ('Koloniya Zastav’ye');
insert into [dbo].[region] (name) values ('Nyakhachava');
insert into [dbo].[region] (name) values ('Murree');
insert into [dbo].[region] (name) values ('Wenping');
insert into [dbo].[region] (name) values ('Nanmen');
insert into [dbo].[region] (name) values ('Naro-Fominsk');
insert into [dbo].[region] (name) values ('Noginsk-9');
insert into [dbo].[region] (name) values ('Daitōchō');
insert into [dbo].[region] (name) values ('Privlaka');
insert into [dbo].[region] (name) values ('Padej');
insert into [dbo].[region] (name) values ('Xianan');
insert into [dbo].[region] (name) values ('Hengshan');
insert into [dbo].[region] (name) values ('Dali');
insert into [dbo].[region] (name) values ('Ngulahan');
insert into [dbo].[region] (name) values ('Bohai');
insert into [dbo].[region] (name) values ('Radoboj');
insert into [dbo].[region] (name) values ('Lesnyye Polyany');
insert into [dbo].[region] (name) values ('Tula');
insert into [dbo].[region] (name) values ('Nongba');
insert into [dbo].[region] (name) values ('Äänekoski');
insert into [dbo].[region] (name) values ('San Francisco');
insert into [dbo].[region] (name) values ('Kalangan');
insert into [dbo].[region] (name) values ('Aleksandrovka');
insert into [dbo].[region] (name) values ('Balayan');
insert into [dbo].[region] (name) values ('Kebonan');
insert into [dbo].[region] (name) values ('Tuguan');
insert into [dbo].[region] (name) values ('Vahdat');
insert into [dbo].[region] (name) values ('Habartov');
insert into [dbo].[region] (name) values ('Dongshi');
insert into [dbo].[region] (name) values ('Xijiao');
insert into [dbo].[region] (name) values ('Cai Doi Vam');
insert into [dbo].[region] (name) values ('Beauvais');
insert into [dbo].[region] (name) values ('Bueng Samakkhi');
insert into [dbo].[region] (name) values ('Caleta Olivia');
insert into [dbo].[region] (name) values ('Gapuk');
insert into [dbo].[region] (name) values ('Kotabunan');
insert into [dbo].[region] (name) values ('Pacarkeling');
insert into [dbo].[region] (name) values ('Carvalhal da Aroeira');
insert into [dbo].[region] (name) values ('Al Qurayn');
insert into [dbo].[region] (name) values ('Mohoro');
insert into [dbo].[region] (name) values ('Huangjin');
insert into [dbo].[region] (name) values ('Oughterard');
insert into [dbo].[region] (name) values ('Sịa');
insert into [dbo].[region] (name) values ('Łęknica');
insert into [dbo].[region] (name) values ('Antang');
insert into [dbo].[region] (name) values ('El Cortezo');
insert into [dbo].[region] (name) values ('Port-à-Piment');
insert into [dbo].[region] (name) values ('Da’anshan');
insert into [dbo].[region] (name) values ('Novi Sad');
insert into [dbo].[region] (name) values ('Al ‘Awjah');
insert into [dbo].[region] (name) values ('Campo Belo');
insert into [dbo].[region] (name) values ('Zhongben');
insert into [dbo].[region] (name) values ('Yên Lạc');
insert into [dbo].[region] (name) values ('Bello');
insert into [dbo].[region] (name) values ('São Sebastião');
insert into [dbo].[region] (name) values ('Despotovac');
insert into [dbo].[region] (name) values ('Qiping');
insert into [dbo].[region] (name) values ('Dayuan');
insert into [dbo].[region] (name) values ('Taipingying');
insert into [dbo].[region] (name) values ('Llauta');
insert into [dbo].[region] (name) values ('Bumba');
insert into [dbo].[region] (name) values ('Trollhättan');
insert into [dbo].[region] (name) values ('Wufeng');
insert into [dbo].[region] (name) values ('Zhangdu');
insert into [dbo].[region] (name) values ('Oyskhara');
insert into [dbo].[region] (name) values ('Baculin');
insert into [dbo].[region] (name) values ('Krajan Karanganyar');
insert into [dbo].[region] (name) values ('Bergen');
insert into [dbo].[region] (name) values ('Tempursari Wetan');
insert into [dbo].[region] (name) values ('Luofang');
insert into [dbo].[region] (name) values ('Baffa');
insert into [dbo].[region] (name) values ('Kario');
insert into [dbo].[region] (name) values ('Mayma');
insert into [dbo].[region] (name) values ('San Roque');
insert into [dbo].[region] (name) values ('Putukrejo');
insert into [dbo].[region] (name) values ('Pilang');
insert into [dbo].[region] (name) values ('Rancapeundey');
insert into [dbo].[region] (name) values ('Susuman');
insert into [dbo].[region] (name) values ('Girang');
insert into [dbo].[region] (name) values ('Kalmunai');
insert into [dbo].[region] (name) values ('Santo Domingo');
insert into [dbo].[region] (name) values ('Gurra e Vogël');
insert into [dbo].[region] (name) values ('Nizhnepavlovka');
insert into [dbo].[region] (name) values ('Kuala Lumpur');
insert into [dbo].[region] (name) values ('Fengxian');
insert into [dbo].[region] (name) values ('Thị Trấn Thất Khê');
insert into [dbo].[region] (name) values ('Libertad');
insert into [dbo].[region] (name) values ('Hejiayan');
insert into [dbo].[region] (name) values ('Iradan');
insert into [dbo].[region] (name) values ('Sausa');
insert into [dbo].[region] (name) values ('Zvishavane');
insert into [dbo].[region] (name) values ('Fengshan');
insert into [dbo].[region] (name) values ('Esperantina');
insert into [dbo].[region] (name) values ('Bukhovo');
insert into [dbo].[region] (name) values ('Dýšina');
insert into [dbo].[region] (name) values ('Saint-Étienne');
insert into [dbo].[region] (name) values ('Atami');
insert into [dbo].[region] (name) values ('Huatai');
insert into [dbo].[region] (name) values ('Uvarovka');
insert into [dbo].[region] (name) values ('Otofuke');
insert into [dbo].[region] (name) values ('Wola Rębkowska');
insert into [dbo].[region] (name) values ('Pyay');
insert into [dbo].[region] (name) values ('Dashiqiao');
insert into [dbo].[region] (name) values ('Žrnovnica');
insert into [dbo].[region] (name) values ('Krzemienica');
insert into [dbo].[region] (name) values ('La Peña');
insert into [dbo].[region] (name) values ('Västerås');
insert into [dbo].[region] (name) values ('Xiyang');
insert into [dbo].[region] (name) values ('Governor’s Harbour');
insert into [dbo].[region] (name) values ('Canmang');
insert into [dbo].[region] (name) values ('Dupi');
insert into [dbo].[region] (name) values ('Sáchica');
insert into [dbo].[region] (name) values ('Ögöömör');
insert into [dbo].[region] (name) values ('Oyo');
insert into [dbo].[region] (name) values ('Bélel');
insert into [dbo].[region] (name) values ('Svalyava');
insert into [dbo].[region] (name) values ('Borbon');
insert into [dbo].[region] (name) values ('Mach');
insert into [dbo].[region] (name) values ('Haodi');
insert into [dbo].[region] (name) values ('San Antonio Oeste');
insert into [dbo].[region] (name) values ('Gbawe');
insert into [dbo].[region] (name) values ('Naḥf');
insert into [dbo].[region] (name) values ('Pondokwungu');
insert into [dbo].[region] (name) values ('Danao');
insert into [dbo].[region] (name) values ('Kuala Terengganu');
insert into [dbo].[region] (name) values ('La Unión');
insert into [dbo].[region] (name) values ('Loma Bonita');
insert into [dbo].[region] (name) values ('Rosario de Mora');
insert into [dbo].[region] (name) values ('Ila Orangun');
insert into [dbo].[region] (name) values ('Vredendal');
insert into [dbo].[region] (name) values ('Bairro');
insert into [dbo].[region] (name) values ('Gniezno');
insert into [dbo].[region] (name) values ('Tanda');
insert into [dbo].[region] (name) values ('Lysyanka');
insert into [dbo].[region] (name) values ('Bantarsari Kulon');
insert into [dbo].[region] (name) values ('Itacorubi');
insert into [dbo].[region] (name) values ('Morelos');
insert into [dbo].[region] (name) values ('Arbois');
insert into [dbo].[region] (name) values ('Swift Current');
insert into [dbo].[region] (name) values ('Puutuga');
insert into [dbo].[region] (name) values ('Barras');
insert into [dbo].[region] (name) values ('Nangerang');
insert into [dbo].[region] (name) values ('Pahonjean');
insert into [dbo].[region] (name) values ('Yacimiento Río Turbio');
insert into [dbo].[region] (name) values ('Nifuboko');
insert into [dbo].[region] (name) values ('Richmond');
insert into [dbo].[region] (name) values ('Villa Serrano');
insert into [dbo].[region] (name) values ('Fatubia');
insert into [dbo].[region] (name) values ('Bangkal');
insert into [dbo].[region] (name) values ('Yangce');
insert into [dbo].[region] (name) values ('Cherëmushki');
insert into [dbo].[region] (name) values ('Lamalewo');
insert into [dbo].[region] (name) values ('Tongtuan');
insert into [dbo].[region] (name) values ('Darya Boyi');
insert into [dbo].[region] (name) values ('Qingzhou');
insert into [dbo].[region] (name) values ('Tiannan');
insert into [dbo].[region] (name) values ('Uddevalla');
insert into [dbo].[region] (name) values ('Caldas da Felgueira');
insert into [dbo].[region] (name) values ('Banjar Sengguan');
insert into [dbo].[region] (name) values ('Cayenne');
insert into [dbo].[region] (name) values ('Yong’an');
insert into [dbo].[region] (name) values ('Salavan');
insert into [dbo].[region] (name) values ('Singosari');
insert into [dbo].[region] (name) values ('Nenagh');
insert into [dbo].[region] (name) values ('Kurjan');
insert into [dbo].[region] (name) values ('Aţ Ţawīlah');
insert into [dbo].[region] (name) values ('Ngadri');
insert into [dbo].[region] (name) values ('Pitanga');
insert into [dbo].[region] (name) values ('Lins');
insert into [dbo].[region] (name) values ('Qarāwat Banī Zayd');
insert into [dbo].[region] (name) values ('Bancak Wetan');
insert into [dbo].[region] (name) values ('Guaçuí');
insert into [dbo].[region] (name) values ('Ban Lŭng');
insert into [dbo].[region] (name) values ('Roissy Charles-de-Gaulle');
insert into [dbo].[region] (name) values ('Geoktschai');
insert into [dbo].[region] (name) values ('Mossoró');
insert into [dbo].[region] (name) values ('Qimantage');
insert into [dbo].[region] (name) values ('Río Limpio');
insert into [dbo].[region] (name) values ('Las Piñas');
insert into [dbo].[region] (name) values ('Mingshui');
insert into [dbo].[region] (name) values ('Prosperous');
insert into [dbo].[region] (name) values ('Dongpu');
insert into [dbo].[region] (name) values ('Paso de los Libres');
insert into [dbo].[region] (name) values ('Antsirabe');
insert into [dbo].[region] (name) values ('Calubcub Dos');
insert into [dbo].[region] (name) values ('Buinsk');
insert into [dbo].[region] (name) values ('Hannō');
insert into [dbo].[region] (name) values ('Klatovy');
insert into [dbo].[region] (name) values ('Tanjay');
insert into [dbo].[region] (name) values ('Janeng');
insert into [dbo].[region] (name) values ('Cabiguan');
insert into [dbo].[region] (name) values ('Thuận Nam');
insert into [dbo].[region] (name) values ('Azinhal');
insert into [dbo].[region] (name) values ('Grenoble');
insert into [dbo].[region] (name) values ('Eastern Suburbs Mc');
insert into [dbo].[region] (name) values ('Masis');
insert into [dbo].[region] (name) values ('Ağdam');
insert into [dbo].[region] (name) values ('Sé');
insert into [dbo].[region] (name) values ('Yurino');
insert into [dbo].[region] (name) values ('Jinshi');
insert into [dbo].[region] (name) values ('Toledo');
insert into [dbo].[region] (name) values ('Colima');
insert into [dbo].[region] (name) values ('Sampaloc');
insert into [dbo].[region] (name) values ('Kamyanyuki');
insert into [dbo].[region] (name) values ('Fengshan');
insert into [dbo].[region] (name) values ('Dong’an');
insert into [dbo].[region] (name) values ('Embu');
insert into [dbo].[region] (name) values ('Da’an');
insert into [dbo].[region] (name) values ('Zürich');
insert into [dbo].[region] (name) values ('Cantaura');
insert into [dbo].[region] (name) values ('Minneapolis');
insert into [dbo].[region] (name) values ('Lacroix-Saint-Ouen');
insert into [dbo].[region] (name) values ('Magtangol');
insert into [dbo].[region] (name) values ('Tarikolot');
insert into [dbo].[region] (name) values ('Brooklyn');
insert into [dbo].[region] (name) values ('Roudnice nad Labem');
insert into [dbo].[region] (name) values ('Calimete');
insert into [dbo].[region] (name) values ('Sundsvall');
insert into [dbo].[region] (name) values ('Rousínov');
insert into [dbo].[region] (name) values ('Carora');
insert into [dbo].[region] (name) values ('Lanas');
insert into [dbo].[region] (name) values ('Balkanabat');
insert into [dbo].[region] (name) values ('São Luís do Quitunde');
insert into [dbo].[region] (name) values ('Zaandam');
insert into [dbo].[region] (name) values ('Cañasgordas');
insert into [dbo].[region] (name) values ('Gradec');
insert into [dbo].[region] (name) values ('Pietermaritzburg');
insert into [dbo].[region] (name) values ('Yangqiaodian');
insert into [dbo].[region] (name) values ('Seria');
insert into [dbo].[region] (name) values ('Auxerre');
insert into [dbo].[region] (name) values ('Hājīganj');
insert into [dbo].[region] (name) values ('Pacov');
insert into [dbo].[region] (name) values ('Vinhas');
insert into [dbo].[region] (name) values ('Skärholmen');
insert into [dbo].[region] (name) values ('Yangdang');
insert into [dbo].[region] (name) values ('Shimen');
insert into [dbo].[region] (name) values ('Denver');
insert into [dbo].[region] (name) values ('Blinsung');
insert into [dbo].[region] (name) values ('Loboniki');
insert into [dbo].[region] (name) values ('Quiches');
insert into [dbo].[region] (name) values ('Phú Mỹ');
insert into [dbo].[region] (name) values ('Żarki');
insert into [dbo].[region] (name) values ('Bački Petrovac');
insert into [dbo].[region] (name) values ('Macari');
insert into [dbo].[region] (name) values ('Duwakkandung');
insert into [dbo].[region] (name) values ('Oneop');
insert into [dbo].[region] (name) values ('Dobrich');
insert into [dbo].[region] (name) values ('Muff');
insert into [dbo].[region] (name) values ('Nanyue');
insert into [dbo].[region] (name) values ('Miribanteng');
insert into [dbo].[region] (name) values ('Nerópolis');
insert into [dbo].[region] (name) values ('Santa Clara');
insert into [dbo].[region] (name) values ('Argenteuil');
insert into [dbo].[region] (name) values ('Dromiskin');
insert into [dbo].[region] (name) values ('Ukhta');
insert into [dbo].[region] (name) values ('Karajeun');
insert into [dbo].[region] (name) values ('Nicoya');
insert into [dbo].[region] (name) values ('Banggel');
insert into [dbo].[region] (name) values ('Frankfurt am Main');
insert into [dbo].[region] (name) values ('Tashtagol');
insert into [dbo].[region] (name) values ('Sabang');
insert into [dbo].[region] (name) values ('Caigongzhuang');
insert into [dbo].[region] (name) values ('Kakamega');
insert into [dbo].[region] (name) values ('Ajung');
insert into [dbo].[region] (name) values ('Zumarraga');
insert into [dbo].[region] (name) values ('Yanghu');
insert into [dbo].[region] (name) values ('Bajina Bašta');
insert into [dbo].[region] (name) values ('Ternate');
insert into [dbo].[region] (name) values ('Fezna');
insert into [dbo].[region] (name) values ('Ngedhusuba');
insert into [dbo].[region] (name) values ('Bizhou');
insert into [dbo].[region] (name) values ('Shatian');
insert into [dbo].[region] (name) values ('Konduga');
insert into [dbo].[region] (name) values ('Gaopai');
insert into [dbo].[region] (name) values ('Mokotów');
insert into [dbo].[region] (name) values ('Oliveira');
insert into [dbo].[region] (name) values ('Futuroscope');
insert into [dbo].[region] (name) values ('Alexandria');
insert into [dbo].[region] (name) values ('Tambak');
insert into [dbo].[region] (name) values ('Xipi');
insert into [dbo].[region] (name) values ('Baiyun');
insert into [dbo].[region] (name) values ('Xindian');
insert into [dbo].[region] (name) values ('Raposos');
insert into [dbo].[region] (name) values ('Belsk Duży');
insert into [dbo].[region] (name) values ('Shijiang');
insert into [dbo].[region] (name) values ('Franceville');
insert into [dbo].[region] (name) values ('Sājir');
insert into [dbo].[region] (name) values ('San Narciso');
insert into [dbo].[region] (name) values ('El Paso');
insert into [dbo].[region] (name) values ('Glan');
insert into [dbo].[region] (name) values ('Taxisco');
insert into [dbo].[region] (name) values ('Peshtera');
insert into [dbo].[region] (name) values ('Antopal’');
insert into [dbo].[region] (name) values ('Salinas');
insert into [dbo].[region] (name) values ('La Guadalupe');
insert into [dbo].[region] (name) values ('Strasbourg');
insert into [dbo].[region] (name) values ('Shuangtang');
insert into [dbo].[region] (name) values ('Bojonglarang');
insert into [dbo].[region] (name) values ('Brooklyn');
insert into [dbo].[region] (name) values ('Wageningen');
insert into [dbo].[region] (name) values ('Gualeguaychú');
insert into [dbo].[region] (name) values ('Sumqayıt');
insert into [dbo].[region] (name) values ('Hausjärvi');
insert into [dbo].[region] (name) values ('Grzechynia');
insert into [dbo].[region] (name) values ('Umi');
insert into [dbo].[region] (name) values ('Cabrela');
insert into [dbo].[region] (name) values ('Stockton');
insert into [dbo].[region] (name) values ('Pining');
insert into [dbo].[region] (name) values ('Kalidawir');
insert into [dbo].[region] (name) values ('Poniatowa');
insert into [dbo].[region] (name) values ('Cunliji');
insert into [dbo].[region] (name) values ('Xiangquan');
insert into [dbo].[region] (name) values ('Živinice');
insert into [dbo].[region] (name) values ('Rājshāhi');
insert into [dbo].[region] (name) values ('Bom Jesus da Lapa');
insert into [dbo].[region] (name) values ('Ksawerów');
insert into [dbo].[region] (name) values ('Noginsk-9');
insert into [dbo].[region] (name) values ('Houston');
insert into [dbo].[region] (name) values ('Jagabaya Dua');
insert into [dbo].[region] (name) values ('Kadipaten');
insert into [dbo].[region] (name) values ('Heshang');
insert into [dbo].[region] (name) values ('Xinlin');
insert into [dbo].[region] (name) values ('Thanh Xuân');
insert into [dbo].[region] (name) values ('Praia Grande');
insert into [dbo].[region] (name) values ('Melíssia');
insert into [dbo].[region] (name) values ('Shi’ao');
insert into [dbo].[region] (name) values ('Skoghall');
insert into [dbo].[region] (name) values ('Suntar');
insert into [dbo].[region] (name) values ('Nuyno');
insert into [dbo].[region] (name) values ('Pedra Azul');
insert into [dbo].[region] (name) values ('Tân Châu');
insert into [dbo].[region] (name) values ('Shypyntsi');
insert into [dbo].[region] (name) values ('Baganhilir');
insert into [dbo].[region] (name) values ('Plei Kần');
insert into [dbo].[region] (name) values ('Carregado');
insert into [dbo].[region] (name) values ('Citeureup');
insert into [dbo].[region] (name) values ('Kilju');
insert into [dbo].[region] (name) values ('Serpukhov');
insert into [dbo].[region] (name) values ('Jacksonville');
insert into [dbo].[region] (name) values ('Marcala');
insert into [dbo].[region] (name) values ('Kansas City');
insert into [dbo].[region] (name) values ('Billdal');
insert into [dbo].[region] (name) values ('La Libertad');
insert into [dbo].[region] (name) values ('Omiš');
insert into [dbo].[region] (name) values ('Bitam');
insert into [dbo].[region] (name) values ('Sumbawa Besar');
insert into [dbo].[region] (name) values ('Dębowa Łąka');
insert into [dbo].[region] (name) values ('Kota Bharu');
insert into [dbo].[region] (name) values ('Pulau Tiga');
insert into [dbo].[region] (name) values ('Bidbid');
insert into [dbo].[region] (name) values ('Tucurú');
insert into [dbo].[region] (name) values ('Point Hill');
insert into [dbo].[region] (name) values ('Arroyo Seco');
insert into [dbo].[region] (name) values ('Brusque');
insert into [dbo].[region] (name) values ('Ngoc Hon Doc');
insert into [dbo].[region] (name) values ('Dakoutun');
insert into [dbo].[region] (name) values ('Gbarnga');
insert into [dbo].[region] (name) values ('Nangalimang');
insert into [dbo].[region] (name) values ('Bayan Qagan');
insert into [dbo].[region] (name) values ('Niamey');
insert into [dbo].[region] (name) values ('Kasreman');
insert into [dbo].[region] (name) values ('Labrador');
insert into [dbo].[region] (name) values ('Terawas');
insert into [dbo].[region] (name) values ('Pamanukan');
insert into [dbo].[region] (name) values ('Margasari');
insert into [dbo].[region] (name) values ('Sambopinggir');
insert into [dbo].[region] (name) values ('Punta Cana');
insert into [dbo].[region] (name) values ('Cerro');
insert into [dbo].[region] (name) values ('Atalaia');
insert into [dbo].[region] (name) values ('Kampunglistrik');
insert into [dbo].[region] (name) values ('Ad Dawādimī');
insert into [dbo].[region] (name) values ('Nizhniy Tagil');
insert into [dbo].[region] (name) values ('Íos');
insert into [dbo].[region] (name) values ('Décines-Charpieu');
insert into [dbo].[region] (name) values ('Noisy-le-Grand');
insert into [dbo].[region] (name) values ('La Loma');
insert into [dbo].[region] (name) values ('Ust’-Kalmanka');
insert into [dbo].[region] (name) values ('Béziers');
insert into [dbo].[region] (name) values ('Närpes');
insert into [dbo].[region] (name) values ('Semenivka');
insert into [dbo].[region] (name) values ('Otradnyy');
insert into [dbo].[region] (name) values ('Jiangxiangzhen');
insert into [dbo].[region] (name) values ('Wirodayan');
insert into [dbo].[region] (name) values ('Chengnan');
insert into [dbo].[region] (name) values ('Sobreira');
insert into [dbo].[region] (name) values ('Vadstena');
insert into [dbo].[region] (name) values ('Macapá');
insert into [dbo].[region] (name) values ('Ancona');
insert into [dbo].[region] (name) values ('Lhoknga');
insert into [dbo].[region] (name) values ('Jargalant');
insert into [dbo].[region] (name) values ('Mendez-Nuñez');
insert into [dbo].[region] (name) values ('Ouadda');
insert into [dbo].[region] (name) values ('Bor');
insert into [dbo].[region] (name) values ('Kebonagung');
insert into [dbo].[region] (name) values ('Pore');
insert into [dbo].[region] (name) values ('Nart');
insert into [dbo].[region] (name) values ('Potoni');
insert into [dbo].[region] (name) values ('Kudymkar');
insert into [dbo].[region] (name) values ('Naberezhnyye Chelny');
insert into [dbo].[region] (name) values ('Hagonoy');
insert into [dbo].[region] (name) values ('Grootfontein');
insert into [dbo].[region] (name) values ('Paris 19');
insert into [dbo].[region] (name) values ('Palaiochóri');
insert into [dbo].[region] (name) values ('Longjumeau');
insert into [dbo].[region] (name) values ('Jagiełła');
insert into [dbo].[region] (name) values ('Jati');
insert into [dbo].[region] (name) values ('Gorzyczki');
insert into [dbo].[region] (name) values ('Binkolo');
insert into [dbo].[region] (name) values ('Borik');
insert into [dbo].[region] (name) values ('Geldrop');
insert into [dbo].[region] (name) values ('Villa Cañás');
insert into [dbo].[region] (name) values ('Manolás');
insert into [dbo].[region] (name) values ('Cintawana');
insert into [dbo].[region] (name) values ('Vrede');
insert into [dbo].[region] (name) values ('Bestala');
insert into [dbo].[region] (name) values ('Korolevo');
insert into [dbo].[region] (name) values ('Garwolin');
insert into [dbo].[region] (name) values ('Luhans’ke');
insert into [dbo].[region] (name) values ('Luopu');
insert into [dbo].[region] (name) values ('João Pessoa');
insert into [dbo].[region] (name) values ('Baghdad');
insert into [dbo].[region] (name) values ('Attard');
insert into [dbo].[region] (name) values ('Valence');
insert into [dbo].[region] (name) values ('Karpinsk');
insert into [dbo].[region] (name) values ('Janeng');
insert into [dbo].[region] (name) values ('Pirapora');
insert into [dbo].[region] (name) values ('‘Anjarah');
insert into [dbo].[region] (name) values ('Vulcan');
insert into [dbo].[region] (name) values ('Ratchathewi');
insert into [dbo].[region] (name) values ('Krasnaya Polyana');
insert into [dbo].[region] (name) values ('Fredericton');
insert into [dbo].[region] (name) values ('Yuncao');
insert into [dbo].[region] (name) values ('Jiangkou');
insert into [dbo].[region] (name) values ('Yuping');
insert into [dbo].[region] (name) values ('Matayumtayum');
insert into [dbo].[region] (name) values ('Khondāb');
insert into [dbo].[region] (name) values ('Zongluzui');
insert into [dbo].[region] (name) values ('Sivers’k');
insert into [dbo].[region] (name) values ('Trzebieszów');
insert into [dbo].[region] (name) values ('Tbilisskaya');
insert into [dbo].[region] (name) values ('Bromma');
insert into [dbo].[region] (name) values ('Kovilj');
insert into [dbo].[region] (name) values ('Soledad');
insert into [dbo].[region] (name) values ('Wojciechów');
insert into [dbo].[region] (name) values ('Neuville');
insert into [dbo].[region] (name) values ('Bayantal');
insert into [dbo].[region] (name) values ('Zhenshan');
insert into [dbo].[region] (name) values ('Yug');
insert into [dbo].[region] (name) values ('Guarda Nova');
insert into [dbo].[region] (name) values ('Paracuru');
insert into [dbo].[region] (name) values ('Ukrainka');
insert into [dbo].[region] (name) values ('Adelaide Mail Centre');
insert into [dbo].[region] (name) values ('Nkove');
insert into [dbo].[region] (name) values ('Żurowa');
insert into [dbo].[region] (name) values ('Obrera');
insert into [dbo].[region] (name) values ('Lefortovo');
insert into [dbo].[region] (name) values ('Tanahgrogot');
insert into [dbo].[region] (name) values ('Pryluky');
insert into [dbo].[region] (name) values ('Karanganyar');
insert into [dbo].[region] (name) values ('Xinsheng');
insert into [dbo].[region] (name) values ('Manikchari');
insert into [dbo].[region] (name) values ('Faraulep');
insert into [dbo].[region] (name) values ('Laagri');
insert into [dbo].[region] (name) values ('Tāybād');
insert into [dbo].[region] (name) values ('Tsaghveri');
insert into [dbo].[region] (name) values ('Nový Malín');
insert into [dbo].[region] (name) values ('Rinbung');
insert into [dbo].[region] (name) values ('Tuscaloosa');
insert into [dbo].[region] (name) values ('As Sawdā');
insert into [dbo].[region] (name) values ('Repelón');
insert into [dbo].[region] (name) values ('Logon');
insert into [dbo].[region] (name) values ('Banana Village');
insert into [dbo].[region] (name) values ('Dateng');
insert into [dbo].[region] (name) values ('Zhoushizhuang');
insert into [dbo].[region] (name) values ('Linköping');
insert into [dbo].[region] (name) values ('San Lorenzo');
insert into [dbo].[region] (name) values ('Ōmiya');
insert into [dbo].[region] (name) values ('Baras');
insert into [dbo].[region] (name) values ('Brokopondo');
insert into [dbo].[region] (name) values ('Gurlan');
insert into [dbo].[region] (name) values ('Ibaté');
insert into [dbo].[region] (name) values ('Khairpur');
insert into [dbo].[region] (name) values ('Pathein');
insert into [dbo].[region] (name) values ('Domont');
insert into [dbo].[region] (name) values ('Sayaxché');
insert into [dbo].[region] (name) values ('Sulak');
insert into [dbo].[region] (name) values ('Maringá');
insert into [dbo].[region] (name) values ('Lexington');
insert into [dbo].[region] (name) values ('Krajan');
insert into [dbo].[region] (name) values ('Senahú');
insert into [dbo].[region] (name) values ('Kamojimachō-jōgejima');
insert into [dbo].[region] (name) values ('Lidköping');
insert into [dbo].[region] (name) values ('El Lolo');
insert into [dbo].[region] (name) values ('Zbraslav');
insert into [dbo].[region] (name) values ('Tigaon');
insert into [dbo].[region] (name) values ('Locminé');
insert into [dbo].[region] (name) values ('Tycheró');
insert into [dbo].[region] (name) values ('Jos');
insert into [dbo].[region] (name) values ('Mikhaylovsk');
insert into [dbo].[region] (name) values ('Ngroto');
insert into [dbo].[region] (name) values ('Bayt Sāḩūr');
insert into [dbo].[region] (name) values ('Suresnes');
insert into [dbo].[region] (name) values ('Basīrpur');
insert into [dbo].[region] (name) values ('Poroçan');
insert into [dbo].[region] (name) values ('Ngama');
insert into [dbo].[region] (name) values ('Bayan-Ovoo');
insert into [dbo].[region] (name) values ('Longcheng');
insert into [dbo].[region] (name) values ('Atlanta');
insert into [dbo].[region] (name) values ('Alis');
insert into [dbo].[region] (name) values ('Los Córdobas');
insert into [dbo].[region] (name) values ('Taraju');
insert into [dbo].[region] (name) values ('Huanghe');
insert into [dbo].[region] (name) values ('Guta');
insert into [dbo].[region] (name) values ('Jianguang');
insert into [dbo].[region] (name) values ('Chennevières-sur-Marne');
insert into [dbo].[region] (name) values ('Pirava');
insert into [dbo].[region] (name) values ('Sokol’niki');
insert into [dbo].[region] (name) values ('Naranjos');
insert into [dbo].[region] (name) values ('København');
insert into [dbo].[region] (name) values ('Lagoa');
insert into [dbo].[region] (name) values ('Antas');
insert into [dbo].[region] (name) values ('Saint-Quentin-en-Yvelines');
insert into [dbo].[region] (name) values ('Duqiong');
insert into [dbo].[region] (name) values ('Pedro II');
insert into [dbo].[region] (name) values ('Pittsburgh');
insert into [dbo].[region] (name) values ('Tulle');
insert into [dbo].[region] (name) values ('Petauke');
insert into [dbo].[region] (name) values ('Iznoski');
insert into [dbo].[region] (name) values ('President Roxas');
insert into [dbo].[region] (name) values ('Larochette');
insert into [dbo].[region] (name) values ('Arruda dos Vinhos');
insert into [dbo].[region] (name) values ('Gumawang');
insert into [dbo].[region] (name) values ('Salamanca');
insert into [dbo].[region] (name) values ('Stenungsund');
insert into [dbo].[region] (name) values ('San Francisco');
insert into [dbo].[region] (name) values ('Pākpattan');
insert into [dbo].[region] (name) values ('Wufeng');
insert into [dbo].[region] (name) values ('Hushi');
insert into [dbo].[region] (name) values ('El Arenal');
insert into [dbo].[region] (name) values ('Kraton');
insert into [dbo].[region] (name) values ('Buenavista');
insert into [dbo].[region] (name) values ('Afántou');
insert into [dbo].[region] (name) values ('Hénin-Beaumont');
insert into [dbo].[region] (name) values ('Fonte Boa');
insert into [dbo].[region] (name) values ('Taihe');
insert into [dbo].[region] (name) values ('Wugong');
insert into [dbo].[region] (name) values ('Kangani');
insert into [dbo].[region] (name) values ('Wufeng');
insert into [dbo].[region] (name) values ('Skhodnya');
insert into [dbo].[region] (name) values ('Tapayan');
insert into [dbo].[region] (name) values ('Śliwice');
insert into [dbo].[region] (name) values ('Oslo');
insert into [dbo].[region] (name) values ('Andilamena');
insert into [dbo].[region] (name) values ('Fujioka');
insert into [dbo].[region] (name) values ('Church End');
insert into [dbo].[region] (name) values ('Boston');
insert into [dbo].[region] (name) values ('Barranca de Upía');
insert into [dbo].[region] (name) values ('Dalang');
insert into [dbo].[region] (name) values ('Xichuan');
insert into [dbo].[region] (name) values ('Ximapo');
insert into [dbo].[region] (name) values ('Puerto Rico');
insert into [dbo].[region] (name) values ('Jinluo');
insert into [dbo].[region] (name) values ('Yonkers');
insert into [dbo].[region] (name) values ('Conel');
insert into [dbo].[region] (name) values ('Chernomorets');
insert into [dbo].[region] (name) values ('Siennica Różana');
insert into [dbo].[region] (name) values ('Krajenka');
insert into [dbo].[region] (name) values ('Berovo');
insert into [dbo].[region] (name) values ('Sulak');
insert into [dbo].[region] (name) values ('Yangzhuang');
insert into [dbo].[region] (name) values ('Longquan');
insert into [dbo].[region] (name) values ('Boyle');
insert into [dbo].[region] (name) values ('Višňové');
insert into [dbo].[region] (name) values ('Gia Nghĩa');
insert into [dbo].[region] (name) values ('Al Manshāh');
insert into [dbo].[region] (name) values ('Fier-Çifçi');
insert into [dbo].[region] (name) values ('Baoping');
insert into [dbo].[region] (name) values ('Évreux');
insert into [dbo].[region] (name) values ('Pirallahı');
insert into [dbo].[region] (name) values ('Bastos');
insert into [dbo].[region] (name) values ('Parigi');
insert into [dbo].[region] (name) values ('Qingqu');
insert into [dbo].[region] (name) values ('Sobreira');
insert into [dbo].[region] (name) values ('Yishui');
insert into [dbo].[region] (name) values ('Longjumeau');
insert into [dbo].[region] (name) values ('Divinópolis');
insert into [dbo].[region] (name) values ('Lefkoniko');
insert into [dbo].[region] (name) values ('Leiguan');
insert into [dbo].[region] (name) values ('Jiangpan');
insert into [dbo].[region] (name) values ('Icheon-si');
insert into [dbo].[region] (name) values ('Leku');
insert into [dbo].[region] (name) values ('Buzen');
insert into [dbo].[region] (name) values ('São Domingos');
insert into [dbo].[region] (name) values ('Catriló');
insert into [dbo].[region] (name) values ('Haguenau');
insert into [dbo].[region] (name) values ('Xinan');
insert into [dbo].[region] (name) values ('Ostrówek');
insert into [dbo].[region] (name) values ('Jeruk');
insert into [dbo].[region] (name) values ('Boissevain');
insert into [dbo].[region] (name) values ('Vienna');
insert into [dbo].[region] (name) values ('Wangcun');
insert into [dbo].[region] (name) values ('Vostryakovo');
insert into [dbo].[region] (name) values ('Slobodskoy');
insert into [dbo].[region] (name) values ('Cergy-Pontoise');
insert into [dbo].[region] (name) values ('Toumodi');
insert into [dbo].[region] (name) values ('Balaoang');
insert into [dbo].[region] (name) values ('Beringinjaya');
insert into [dbo].[region] (name) values ('Tierp');
insert into [dbo].[region] (name) values ('Pukou');
insert into [dbo].[region] (name) values ('Watrous');
insert into [dbo].[region] (name) values ('Mengla');
insert into [dbo].[region] (name) values ('Bilyarsk');
insert into [dbo].[region] (name) values ('Iktābah');
insert into [dbo].[region] (name) values ('Pécs');
insert into [dbo].[region] (name) values ('Zhijin');
insert into [dbo].[region] (name) values ('Yamparáez');
insert into [dbo].[region] (name) values ('Gostivar');
insert into [dbo].[region] (name) values ('Fálanna');
insert into [dbo].[region] (name) values ('Sidi Yahia el Gharb');
insert into [dbo].[region] (name) values ('Xuanma');
insert into [dbo].[region] (name) values ('Wangbuzhuang');
insert into [dbo].[region] (name) values ('Baguim do Monte');
insert into [dbo].[region] (name) values ('Bindura');
insert into [dbo].[region] (name) values ('Molagavita');
insert into [dbo].[region] (name) values ('Skanör');
insert into [dbo].[region] (name) values ('Stockholm');
insert into [dbo].[region] (name) values ('Vitry-sur-Seine');
insert into [dbo].[region] (name) values ('Huacrapuquio');
insert into [dbo].[region] (name) values ('Fengcun');
insert into [dbo].[region] (name) values ('Västerås');
insert into [dbo].[region] (name) values ('Oujda');
insert into [dbo].[region] (name) values ('Zhangping');
insert into [dbo].[region] (name) values ('Kalepasan');
insert into [dbo].[region] (name) values ('Thị Trấn Tà Lùng');
insert into [dbo].[region] (name) values ('Monywa');
insert into [dbo].[region] (name) values ('Newport');
insert into [dbo].[region] (name) values ('Aldeia da Bela Vista');
insert into [dbo].[region] (name) values ('Guandi');
insert into [dbo].[region] (name) values ('Tapayan');
insert into [dbo].[region] (name) values ('Buliwao');
insert into [dbo].[region] (name) values ('Heshan');
insert into [dbo].[region] (name) values ('Vardablur');
insert into [dbo].[region] (name) values ('Demir Hisar');
insert into [dbo].[region] (name) values ('Nancaicun');
insert into [dbo].[region] (name) values ('Thongwa');
insert into [dbo].[region] (name) values ('Bagnères-de-Bigorre');
insert into [dbo].[region] (name) values ('Ilandža');
insert into [dbo].[region] (name) values ('Marquard');
insert into [dbo].[region] (name) values ('Chunjiang');
insert into [dbo].[region] (name) values ('Laban');
insert into [dbo].[region] (name) values ('Krajan Sumurtawang');
insert into [dbo].[region] (name) values ('Xintun');
insert into [dbo].[region] (name) values ('Omuthiya');
insert into [dbo].[region] (name) values ('Waihi Beach');
insert into [dbo].[region] (name) values ('Sabá');
insert into [dbo].[region] (name) values ('Roczyny');
insert into [dbo].[region] (name) values ('Pulau Pinang');
insert into [dbo].[region] (name) values ('Guishan');
insert into [dbo].[region] (name) values ('Fuji');
insert into [dbo].[region] (name) values ('Le Puy-en-Velay');
insert into [dbo].[region] (name) values ('Dayong');
insert into [dbo].[region] (name) values ('Peñarrubia');
insert into [dbo].[region] (name) values ('Minggang');
insert into [dbo].[region] (name) values ('Algarrobo');
insert into [dbo].[region] (name) values ('Lidingö');
insert into [dbo].[region] (name) values ('Qincheng');
insert into [dbo].[region] (name) values ('Vũ Quang');
insert into [dbo].[region] (name) values ('Dno');
insert into [dbo].[region] (name) values ('Chorkówka');
insert into [dbo].[region] (name) values ('Quinipot');
insert into [dbo].[region] (name) values ('Kacha');
insert into [dbo].[region] (name) values ('Azueira');
insert into [dbo].[region] (name) values ('Houzhai');
insert into [dbo].[region] (name) values ('Porto Feliz');
insert into [dbo].[region] (name) values ('Itaqui');
insert into [dbo].[region] (name) values ('Kolsh');
insert into [dbo].[region] (name) values ('Votkinsk');
insert into [dbo].[region] (name) values ('Segovia');
insert into [dbo].[region] (name) values ('Rivesaltes');
insert into [dbo].[region] (name) values ('Khánh Hải');
insert into [dbo].[region] (name) values ('Kangar');
insert into [dbo].[region] (name) values ('San Ramon');
insert into [dbo].[region] (name) values ('Ibarra');
insert into [dbo].[region] (name) values ('Camilo Aldao');
insert into [dbo].[region] (name) values ('Guzhuyingzi');
insert into [dbo].[region] (name) values ('Shuangkou');
insert into [dbo].[region] (name) values ('Buzovna');
insert into [dbo].[region] (name) values ('Yanji');
insert into [dbo].[region] (name) values ('Kihancha');
insert into [dbo].[region] (name) values ('Sala');
insert into [dbo].[region] (name) values ('Raša');
insert into [dbo].[region] (name) values ('Baizhu');
insert into [dbo].[region] (name) values ('Tanahwurung');
insert into [dbo].[region] (name) values ('Yenagoa');
insert into [dbo].[region] (name) values ('Verbilki');
insert into [dbo].[region] (name) values ('Ningzhong');
insert into [dbo].[region] (name) values ('Baiyun');
insert into [dbo].[region] (name) values ('Changpu');
insert into [dbo].[region] (name) values ('Dhībīn');
insert into [dbo].[region] (name) values ('Watulimo');
insert into [dbo].[region] (name) values ('Bhopālwāla');
insert into [dbo].[region] (name) values ('Baimaqiao');
insert into [dbo].[region] (name) values ('Terang');
insert into [dbo].[region] (name) values ('Mandalgovi');
insert into [dbo].[region] (name) values ('Tõrva');
insert into [dbo].[region] (name) values ('San Pedro');
insert into [dbo].[region] (name) values ('La Cruz de Taratara');
insert into [dbo].[region] (name) values ('Yongchang');
insert into [dbo].[region] (name) values ('Vila Verde');
insert into [dbo].[region] (name) values ('Tuwa');
insert into [dbo].[region] (name) values ('Laibin');
insert into [dbo].[region] (name) values ('Höfn');
insert into [dbo].[region] (name) values ('Ibara');
insert into [dbo].[region] (name) values ('Tame');
insert into [dbo].[region] (name) values ('Santo Isidro');
insert into [dbo].[region] (name) values ('Igunga');
insert into [dbo].[region] (name) values ('Kavarna');
insert into [dbo].[region] (name) values ('Pagaden');
insert into [dbo].[region] (name) values ('Shaozhai');
insert into [dbo].[region] (name) values ('Kýthnos');
insert into [dbo].[region] (name) values ('Gusong');
insert into [dbo].[region] (name) values ('Komatsu');
insert into [dbo].[region] (name) values ('Liangwangzhuang');
insert into [dbo].[region] (name) values ('Khadzhalmakhi');
insert into [dbo].[region] (name) values ('Karangturi');
insert into [dbo].[region] (name) values ('Honkajoki');
insert into [dbo].[region] (name) values ('Weitian');
insert into [dbo].[region] (name) values ('Sundsvall');
insert into [dbo].[region] (name) values ('Tambakbaya');
insert into [dbo].[region] (name) values ('Benito Juarez');
insert into [dbo].[region] (name) values ('Ñuñoa');
insert into [dbo].[region] (name) values ('Chabařovice');
insert into [dbo].[region] (name) values ('Thị Trấn Than Uyên');
insert into [dbo].[region] (name) values ('Derhachi');
insert into [dbo].[region] (name) values ('Lamas');
insert into [dbo].[region] (name) values ('Yixi');
insert into [dbo].[region] (name) values ('Morant Bay');
insert into [dbo].[region] (name) values ('Lapachito');
insert into [dbo].[region] (name) values ('Levuka');
insert into [dbo].[region] (name) values ('Brooklyn');
insert into [dbo].[region] (name) values ('Morcellemont Saint André');
insert into [dbo].[region] (name) values ('Radeče');
insert into [dbo].[region] (name) values ('Almirante');
insert into [dbo].[region] (name) values ('Brusyliv');
insert into [dbo].[region] (name) values ('Marki');
insert into [dbo].[region] (name) values ('Praia da Vagueira');
insert into [dbo].[region] (name) values ('Omaha');
insert into [dbo].[region] (name) values ('Jingzhou');
insert into [dbo].[region] (name) values ('Belén de Umbría');
insert into [dbo].[region] (name) values ('Duas Igrejas');
insert into [dbo].[region] (name) values ('Valky');
insert into [dbo].[region] (name) values ('Ribeirão Pires');
insert into [dbo].[region] (name) values ('Yataity del Norte');
insert into [dbo].[region] (name) values ('Jilma');
insert into [dbo].[region] (name) values ('Thị Trấn Mường Tè');
insert into [dbo].[region] (name) values ('Montbrison');
insert into [dbo].[region] (name) values ('Milevsko');
insert into [dbo].[region] (name) values ('La Vega');
insert into [dbo].[region] (name) values ('Medina');
insert into [dbo].[region] (name) values ('Punta del Este');
insert into [dbo].[region] (name) values ('Seongnam-si');
insert into [dbo].[region] (name) values ('Mawa');
insert into [dbo].[region] (name) values ('Vinež');
insert into [dbo].[region] (name) values ('Kaustinen');
insert into [dbo].[region] (name) values ('Emiliano Zapata');
insert into [dbo].[region] (name) values ('Kawm Ḩamādah');
insert into [dbo].[region] (name) values ('Menlou’ao');
insert into [dbo].[region] (name) values ('Knežica');
insert into [dbo].[region] (name) values ('Santo Domingo');
insert into [dbo].[region] (name) values ('Serednye Vodyane');
insert into [dbo].[region] (name) values ('Fort Myers');
insert into [dbo].[region] (name) values ('Tangkil');
insert into [dbo].[region] (name) values ('San Diego');
insert into [dbo].[region] (name) values ('Stockholm');
insert into [dbo].[region] (name) values ('Oro Timur');
insert into [dbo].[region] (name) values ('Nakhabino');
insert into [dbo].[region] (name) values ('Chrząstowice');
insert into [dbo].[region] (name) values ('Vecpiebalga');
insert into [dbo].[region] (name) values ('Baishan');
insert into [dbo].[region] (name) values ('Villeta');
insert into [dbo].[region] (name) values ('Bolikhan');
insert into [dbo].[region] (name) values ('Pengandonan');
insert into [dbo].[region] (name) values ('Kyankwanzi');
insert into [dbo].[region] (name) values ('Laguilayan');
insert into [dbo].[region] (name) values ('Cherga');
insert into [dbo].[region] (name) values ('Ciawi');
insert into [dbo].[region] (name) values ('Shiqiao');
insert into [dbo].[region] (name) values ('Lagny-sur-Marne');
insert into [dbo].[region] (name) values ('Gornji Breg');
insert into [dbo].[region] (name) values ('Shangyuan');
insert into [dbo].[region] (name) values ('Chengbei');
insert into [dbo].[region] (name) values ('Genting');
insert into [dbo].[region] (name) values ('Chatuchak');
insert into [dbo].[region] (name) values ('Al Ain');
insert into [dbo].[region] (name) values ('Třemošnice');
insert into [dbo].[region] (name) values ('Sandakan');
insert into [dbo].[region] (name) values ('Bozhou');
insert into [dbo].[region] (name) values ('Bridgetown');
insert into [dbo].[region] (name) values ('Maglajani');
insert into [dbo].[region] (name) values ('Ornontowice');
insert into [dbo].[region] (name) values ('Katy');
insert into [dbo].[region] (name) values ('Sokol’niki');
insert into [dbo].[region] (name) values ('Yushang');
insert into [dbo].[region] (name) values ('Bang Kaeo');
insert into [dbo].[region] (name) values ('Khodasy');
insert into [dbo].[region] (name) values ('Tendō');
insert into [dbo].[region] (name) values ('Campo de la Cruz');
insert into [dbo].[region] (name) values ('Huyunxiang');
insert into [dbo].[region] (name) values ('Hezhai');
insert into [dbo].[region] (name) values ('Chubek');
insert into [dbo].[region] (name) values ('Heby');
insert into [dbo].[region] (name) values ('Borovichi');
insert into [dbo].[region] (name) values ('Lacabamba');
insert into [dbo].[region] (name) values ('Betio Village');
insert into [dbo].[region] (name) values ('Saltpond');
insert into [dbo].[region] (name) values ('Calbuco');
insert into [dbo].[region] (name) values ('Barra Mansa');
insert into [dbo].[region] (name) values ('Bystrytsya');
insert into [dbo].[region] (name) values ('Marne-la-Vallée');
insert into [dbo].[region] (name) values ('Abraham’s Bay');
insert into [dbo].[region] (name) values ('Nageswari');
insert into [dbo].[region] (name) values ('Hörby');
insert into [dbo].[region] (name) values ('Sundbyberg');
insert into [dbo].[region] (name) values ('Obispos');
insert into [dbo].[region] (name) values ('Nanling');
insert into [dbo].[region] (name) values ('Kallithéa');
insert into [dbo].[region] (name) values ('Taoyuan');
insert into [dbo].[region] (name) values ('Jāsim');
insert into [dbo].[region] (name) values ('Chiduo');
insert into [dbo].[region] (name) values ('Bengga');
insert into [dbo].[region] (name) values ('Tanshan');
insert into [dbo].[region] (name) values ('Argayash');
insert into [dbo].[region] (name) values ('Belogorsk');
insert into [dbo].[region] (name) values ('Watari');
insert into [dbo].[region] (name) values ('Chile Chico');
insert into [dbo].[region] (name) values ('Kitcharao');
insert into [dbo].[region] (name) values ('Pikalëvo');
insert into [dbo].[region] (name) values ('Coayllo');
insert into [dbo].[region] (name) values ('Guiyang');
