
INSERT INTO [region] ([name]) values ('Afghanistan');
INSERT INTO [region] ([name]) values ('Ã…land Islands');
INSERT INTO [region] ([name]) values ('Albania');
INSERT INTO [region] ([name]) values ('Algeria');
INSERT INTO [region] ([name]) values ('American Samoa');
INSERT INTO [region] ([name]) values ('Andorra');
INSERT INTO [region] ([name]) values ('Angola');
INSERT INTO [region] ([name]) values ('Anguilla');
INSERT INTO [region] ([name]) values ('Antarctica');
INSERT INTO [region] ([name]) values ('Antigua and Barbuda');
INSERT INTO [region] ([name]) values ('Argentina');
INSERT INTO [region] ([name]) values ('Armenia');
INSERT INTO [region] ([name]) values ('Aruba');
INSERT INTO [region] ([name]) values ('Australia');
INSERT INTO [region] ([name]) values ('Austria');
INSERT INTO [region] ([name]) values ('Azerbaijan');
INSERT INTO [region] ([name]) values ('Bahamas');
INSERT INTO [region] ([name]) values ('Bahrain');
INSERT INTO [region] ([name]) values ('Bangladesh');
INSERT INTO [region] ([name]) values ('Barbados');
INSERT INTO [region] ([name]) values ('Belarus');
INSERT INTO [region] ([name]) values ('Belgium');
INSERT INTO [region] ([name]) values ('Belize');
INSERT INTO [region] ([name]) values ('Benin');
INSERT INTO [region] ([name]) values ('Bermuda');
INSERT INTO [region] ([name]) values ('Bhutan');
INSERT INTO [region] ([name]) values ('Bolivia, Plurinational State of');
INSERT INTO [region] ([name]) values ('Bonaire, Sint Eustatius and Saba');
INSERT INTO [region] ([name]) values ('Bosnia and Herzegovina');
INSERT INTO [region] ([name]) values ('Botswana');
INSERT INTO [region] ([name]) values ('Bouvet Island');
INSERT INTO [region] ([name]) values ('Brazil');
INSERT INTO [region] ([name]) values ('British Indian Ocean Territory');
INSERT INTO [region] ([name]) values ('Brunei Darussalam');
INSERT INTO [region] ([name]) values ('Bulgaria');
INSERT INTO [region] ([name]) values ('Burkina Faso');
INSERT INTO [region] ([name]) values ('Burundi');
INSERT INTO [region] ([name]) values ('Cabo Verde');
INSERT INTO [region] ([name]) values ('Cambodia');
INSERT INTO [region] ([name]) values ('Cameroon');
INSERT INTO [region] ([name]) values ('Canada');
INSERT INTO [region] ([name]) values ('Cayman Islands');
INSERT INTO [region] ([name]) values ('Central African Republic');
INSERT INTO [region] ([name]) values ('Chad');
INSERT INTO [region] ([name]) values ('Chile');
INSERT INTO [region] ([name]) values ('China');
INSERT INTO [region] ([name]) values ('Christmas Island');
INSERT INTO [region] ([name]) values ('Cocos (Keeling) Islands');
INSERT INTO [region] ([name]) values ('Colombia');
INSERT INTO [region] ([name]) values ('Comoros');
INSERT INTO [region] ([name]) values ('Congo');
INSERT INTO [region] ([name]) values ('Congo, Democratic Republic of the');
INSERT INTO [region] ([name]) values ('Cook Islands');
INSERT INTO [region] ([name]) values ('Costa Rica');
INSERT INTO [region] ([name]) values ('CÃ´te dIvoire');
INSERT INTO [region] ([name]) values ('Croatia');
INSERT INTO [region] ([name]) values ('Cuba');
INSERT INTO [region] ([name]) values ('CuraÃ§ao');
INSERT INTO [region] ([name]) values ('Cyprus');
INSERT INTO [region] ([name]) values ('Czechia');
INSERT INTO [region] ([name]) values ('Denmark');
INSERT INTO [region] ([name]) values ('Djibouti');
INSERT INTO [region] ([name]) values ('Dominica');
INSERT INTO [region] ([name]) values ('Dominican Republic');
INSERT INTO [region] ([name]) values ('Ecuador');
INSERT INTO [region] ([name]) values ('Egypt');
INSERT INTO [region] ([name]) values ('El Salvador');
INSERT INTO [region] ([name]) values ('Equatorial Guinea');
INSERT INTO [region] ([name]) values ('Eritrea');
INSERT INTO [region] ([name]) values ('Estonia');
INSERT INTO [region] ([name]) values ('Eswatini');
INSERT INTO [region] ([name]) values ('Ethiopia');
INSERT INTO [region] ([name]) values ('Falkland Islands (Malvinas)');
INSERT INTO [region] ([name]) values ('Faroe Islands');
INSERT INTO [region] ([name]) values ('Fiji');
INSERT INTO [region] ([name]) values ('Finland');
INSERT INTO [region] ([name]) values ('France');
INSERT INTO [region] ([name]) values ('French Guiana');
INSERT INTO [region] ([name]) values ('French Polynesia');
INSERT INTO [region] ([name]) values ('French Southern Territories');
INSERT INTO [region] ([name]) values ('Gabon');
INSERT INTO [region] ([name]) values ('Gambia');
INSERT INTO [region] ([name]) values ('Georgia');
INSERT INTO [region] ([name]) values ('Germany');
INSERT INTO [region] ([name]) values ('Ghana');
INSERT INTO [region] ([name]) values ('Gibraltar');
INSERT INTO [region] ([name]) values ('Greece');
INSERT INTO [region] ([name]) values ('Greenland');
INSERT INTO [region] ([name]) values ('Grenada');
INSERT INTO [region] ([name]) values ('Guadeloupe');
INSERT INTO [region] ([name]) values ('Guam');
INSERT INTO [region] ([name]) values ('Guatemala');
INSERT INTO [region] ([name]) values ('Guernsey');
INSERT INTO [region] ([name]) values ('Guinea');
INSERT INTO [region] ([name]) values ('Guinea-Bissau');
INSERT INTO [region] ([name]) values ('Guyana');
INSERT INTO [region] ([name]) values ('Haiti');
INSERT INTO [region] ([name]) values ('Heard Island and McDonald Islands');
INSERT INTO [region] ([name]) values ('Holy See');
INSERT INTO [region] ([name]) values ('Honduras');
INSERT INTO [region] ([name]) values ('Hong Kong');
INSERT INTO [region] ([name]) values ('Hungary');
INSERT INTO [region] ([name]) values ('Iceland');
INSERT INTO [region] ([name]) values ('India');
INSERT INTO [region] ([name]) values ('Indonesia');
INSERT INTO [region] ([name]) values ('Iran, Islamic Republic of');
INSERT INTO [region] ([name]) values ('Iraq');
INSERT INTO [region] ([name]) values ('Ireland');
INSERT INTO [region] ([name]) values ('Isle of Man');
INSERT INTO [region] ([name]) values ('Israel');
INSERT INTO [region] ([name]) values ('Italy');
INSERT INTO [region] ([name]) values ('Jamaica');
INSERT INTO [region] ([name]) values ('Japan');
INSERT INTO [region] ([name]) values ('Jersey');
INSERT INTO [region] ([name]) values ('Jordan');
INSERT INTO [region] ([name]) values ('Kazakhstan');
INSERT INTO [region] ([name]) values ('Kenya');
INSERT INTO [region] ([name]) values ('Kiribati');
INSERT INTO [region] ([name]) values ('Korea, Democratic People"s Republic of');
INSERT INTO [region] ([name]) values ('Korea, Republic of');
INSERT INTO [region] ([name]) values ('Kuwait');
INSERT INTO [region] ([name]) values ('Kyrgyzstan');
INSERT INTO [region] ([name]) values ('Lao People"s Democratic Republic');
INSERT INTO [region] ([name]) values ('Latvia');
INSERT INTO [region] ([name]) values ('Lebanon');
INSERT INTO [region] ([name]) values ('Lesotho');
INSERT INTO [region] ([name]) values ('Liberia');
INSERT INTO [region] ([name]) values ('Libya');
INSERT INTO [region] ([name]) values ('Liechtenstein');
INSERT INTO [region] ([name]) values ('Lithuania');
INSERT INTO [region] ([name]) values ('Luxembourg');
INSERT INTO [region] ([name]) values ('Macao');
INSERT INTO [region] ([name]) values ('Madagascar');
INSERT INTO [region] ([name]) values ('Malawi');
INSERT INTO [region] ([name]) values ('Malaysia');
INSERT INTO [region] ([name]) values ('Maldives');
INSERT INTO [region] ([name]) values ('Mali');
INSERT INTO [region] ([name]) values ('Malta');
INSERT INTO [region] ([name]) values ('Marshall Islands');
INSERT INTO [region] ([name]) values ('Martinique');
INSERT INTO [region] ([name]) values ('Mauritania');
INSERT INTO [region] ([name]) values ('Mauritius');
INSERT INTO [region] ([name]) values ('Mayotte');
INSERT INTO [region] ([name]) values ('Mexico');
INSERT INTO [region] ([name]) values ('Micronesia Federated States of');
INSERT INTO [region] ([name]) values ('Moldova, Republic of');
INSERT INTO [region] ([name]) values ('Monaco');
INSERT INTO [region] ([name]) values ('Mongolia');
INSERT INTO [region] ([name]) values ('Montenegro');
INSERT INTO [region] ([name]) values ('Montserrat');
INSERT INTO [region] ([name]) values ('Morocco');
INSERT INTO [region] ([name]) values ('Mozambique');
INSERT INTO [region] ([name]) values ('Myanmar');
INSERT INTO [region] ([name]) values ('Namibia');
INSERT INTO [region] ([name]) values ('Nauru');
INSERT INTO [region] ([name]) values ('Nepal');
INSERT INTO [region] ([name]) values ('Netherlands, Kingdom of the');
INSERT INTO [region] ([name]) values ('New Caledonia');
INSERT INTO [region] ([name]) values ('New Zealand');
INSERT INTO [region] ([name]) values ('Nicaragua');
INSERT INTO [region] ([name]) values ('Niger');
INSERT INTO [region] ([name]) values ('Nigeria');
INSERT INTO [region] ([name]) values ('Niue');
INSERT INTO [region] ([name]) values ('Norfolk Island');
INSERT INTO [region] ([name]) values ('North Macedonia');
INSERT INTO [region] ([name]) values ('Northern Mariana Islands');
INSERT INTO [region] ([name]) values ('Norway');
INSERT INTO [region] ([name]) values ('Oman');
INSERT INTO [region] ([name]) values ('Pakistan');
INSERT INTO [region] ([name]) values ('Palau');
INSERT INTO [region] ([name]) values ('Palestine, State of');
INSERT INTO [region] ([name]) values ('Panama');
INSERT INTO [region] ([name]) values ('Papua New Guinea');
INSERT INTO [region] ([name]) values ('Paraguay');
INSERT INTO [region] ([name]) values ('Peru');
INSERT INTO [region] ([name]) values ('Philippines');
INSERT INTO [region] ([name]) values ('Pitcairn');
INSERT INTO [region] ([name]) values ('Poland');
INSERT INTO [region] ([name]) values ('Portugal');
INSERT INTO [region] ([name]) values ('Puerto Rico');
INSERT INTO [region] ([name]) values ('Qatar');
INSERT INTO [region] ([name]) values ('RÃunion');
INSERT INTO [region] ([name]) values ('Romania');
INSERT INTO [region] ([name]) values ('Russian Federation');
INSERT INTO [region] ([name]) values ('Rwanda');
INSERT INTO [region] ([name]) values ('Saint BarthÃ©lemy');
INSERT INTO [region] ([name]) values ('Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO [region] ([name]) values ('Saint Kitts and Nevis');
INSERT INTO [region] ([name]) values ('Saint Lucia');
INSERT INTO [region] ([name]) values ('Saint Martin (French part)');
INSERT INTO [region] ([name]) values ('Saint Pierre and Miquelon');
INSERT INTO [region] ([name]) values ('Saint Vincent and the Grenadines');
INSERT INTO [region] ([name]) values ('Samoa');
INSERT INTO [region] ([name]) values ('San Marino');
INSERT INTO [region] ([name]) values ('Sao Tome and Principe');
INSERT INTO [region] ([name]) values ('Saudi Arabia');
INSERT INTO [region] ([name]) values ('Senegal');
INSERT INTO [region] ([name]) values ('Serbia');
INSERT INTO [region] ([name]) values ('Seychelles');
INSERT INTO [region] ([name]) values ('Sierra Leone');
INSERT INTO [region] ([name]) values ('Singapore');
INSERT INTO [region] ([name]) values ('Sint Maarten (Dutch part)');
INSERT INTO [region] ([name]) values ('Slovakia');
INSERT INTO [region] ([name]) values ('Slovenia');
INSERT INTO [region] ([name]) values ('Solomon Islands');
INSERT INTO [region] ([name]) values ('Somalia');
INSERT INTO [region] ([name]) values ('South Africa');
INSERT INTO [region] ([name]) values ('South Georgia and the South Sandwich Islands');
INSERT INTO [region] ([name]) values ('South Sudan');
INSERT INTO [region] ([name]) values ('Spain');
INSERT INTO [region] ([name]) values ('Sri Lanka');
INSERT INTO [region] ([name]) values ('Sudan');
INSERT INTO [region] ([name]) values ('Suriname');
INSERT INTO [region] ([name]) values ('Svalbard and Jan Mayen');
INSERT INTO [region] ([name]) values ('Sweden');
INSERT INTO [region] ([name]) values ('Switzerland');
INSERT INTO [region] ([name]) values ('Syrian Arab Republic');
INSERT INTO [region] ([name]) values ('Taiwan, Province of China');
INSERT INTO [region] ([name]) values ('Tajikistan');
INSERT INTO [region] ([name]) values ('Tanzania, United Republic of');
INSERT INTO [region] ([name]) values ('Thailand');
INSERT INTO [region] ([name]) values ('Timor-Leste');
INSERT INTO [region] ([name]) values ('Togo');
INSERT INTO [region] ([name]) values ('Tokelau');
INSERT INTO [region] ([name]) values ('Tonga');
INSERT INTO [region] ([name]) values ('Trinidad and Tobago');
INSERT INTO [region] ([name]) values ('Tunisia');
INSERT INTO [region] ([name]) values ('TÃ¼rkiye');
INSERT INTO [region] ([name]) values ('Turkmenistan');
INSERT INTO [region] ([name]) values ('Turks and Caicos Islands');
INSERT INTO [region] ([name]) values ('Tuvalu');
INSERT INTO [region] ([name]) values ('Uganda');
INSERT INTO [region] ([name]) values ('Ukraine');
INSERT INTO [region] ([name]) values ('United Arab Emirates');
INSERT INTO [region] ([name]) values ('United Kingdom of Great Britain and Northern Ireland');
INSERT INTO [region] ([name]) values ('United States of America');
INSERT INTO [region] ([name]) values ('United States Minor Outlying Islands');
INSERT INTO [region] ([name]) values ('Uruguay');
INSERT INTO [region] ([name]) values ('Uzbekistan');
INSERT INTO [region] ([name]) values ('Vanuatu');
INSERT INTO [region] ([name]) values ('Venezuela, Bolivarian Republic of');
INSERT INTO [region] ([name]) values ('Viet Nam');
INSERT INTO [region] ([name]) values ('Virgin Islands (British)');
INSERT INTO [region] ([name]) values ('Virgin Islands (U.S.)');
INSERT INTO [region] ([name]) values ('Wallis and Futuna');
INSERT INTO [region] ([name]) values ('Western Sahara');
INSERT INTO [region] ([name]) values ('Yemen');
INSERT INTO [region] ([name]) values ('Zambia');
INSERT INTO [region] ([name]) values ('Zimbabwe');
